# only used by drive.mikufancx.cyou
# replace `include    nginxconfig.io/proxy.conf;` with this file `include    my-patches/faking-proxy-to-drive.conf;`

# see https://developer.aliyun.com/article/604306

sub_filter node005.eucrochet.store drive.mikufancx.cyou; #网站域名，反代域名
sub_filter_once off;#进行替换

#向后端传递访客ip
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#强制定义Referer
proxy_set_header Referer https://node005.eucrochet.store;
#定义主机
proxy_set_header Host node005.eucrochet.store;

proxy_set_header Accept-Encoding "";
proxy_ssl_server_name on; # see https://blog.dianduidian.com/post/nginx%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86%E5%BD%93%E5%90%8E%E7%AB%AF%E4%B8%BAhttps%E6%97%B6%E7%9A%84%E4%B8%80%E4%BA%9B%E7%BB%86%E8%8A%82%E5%92%8C%E5%8E%9F%E7%90%86/