# add `include               my-patches/lobechat-auth-config.conf;` to lobechat.mikufancx.cyou.conf
auth_basic "Private Lobe-Chat";
auth_basic_user_file htpasswd/lobechat.mikufancx.cyou.htpasswd;
# mikuchat -> wowowow