# for proxy that connects to ourself using https
# add `include    my-patches/self-ssl-proxy.conf;` to any site requires tls connection to ourself
# to ourself means the proxied web service is using the same certificate and key to receive TLS connections
proxy_ssl_verify off;
proxy_ssl_certificate /etc/ssl/_.mikufancx.cyou.crt;
proxy_ssl_certificate_key /etc/ssl/_.mikufancx.cyou.key;
proxy_ssl_name $host; # call the proxy server with the url that we connected from, which is the server_name directive, instead of the proxy_name directive
proxy_ssl_server_name on; # need this for proxy to https
proxy_ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
# put into ttrss.mikufancx.cyou.conf reverse proxy block after include