# Deprecated, using others.

# we need a way to debug what is the effective nginx.conf file, otherwise we can't check if using include statement can replace other things
# so far we think it can't, so we just use the default v2ray setting from https://github.com/p4gefau1t/trojan-go/issues/362#issuecomment-876403780
# but we don't have an confident evidences, can't find any related info online either.

# put into ttrss.mikufancx.cyou.conf reverse proxy block before include after proxy_pass
proxy_redirect off;
proxy_cache_bypass "";

proxy_set_header Connection "";
proxy_set_header Host "";

proxy_set_header Connection "upgrade";
proxy_set_header Host rss.mikufancx.cyou; # modified the host to let ttrss happy

proxy_set_header Forwarded "";
proxy_set_header X-Forwarded-Proto "";
proxy_set_header X-Forwarded-Host  "";
proxy_set_header X-Forwarded-Port  "";

include    my-patches/self-ssl-proxy.conf;