# Deprecated, seems like we don't need it anymore

# add `include    my-patches/ttrss-proxy-patch.conf;` into rss site
proxy_set_header  X-Forwarded-Ssl     on;
proxy_set_header  X-Frame-Options     SAMEORIGIN;
proxy_redirect off;