# replace `include    nginxconfig.io/proxy.conf;` with this file `include    my-patches/ws-proxy-faking.conf;` 
# and delete `proxy_set_header Host $host;` in the any websocket-based proxy config file
# we suspect that you can not declear a nginx statement twice with different values, it probably won't work
proxy_redirect off;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade"; # we suspect this is where it makes websocket proxy working for trojan-go and xray
proxy_set_header Host $http_host;
# Show realip in v2ray access.log
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
# proxy_set_header X-Forwarded-Proto $scheme;
