# add `include    my-patches/xray-grpc.conf;` in front of the `location / {` line to add Xray-grpc
# also change the `listen              443 ssl http2;` to `listen              443 ssl http2 so_keepalive=on;`
# not changing it will get a bunch of timeout, https://github.com/XTLS/Xray-core/issues/975#issuecomment-1060598082

client_header_timeout 1h;
keepalive_timeout 1h;

location /miku-server-aouh {
  if ($content_type !~ "application/grpc") {
    return 404;
  }
  client_max_body_size 0; # need to be 0 to not disrupt large file download, see https://github.com/XTLS/Xray-core/issues/975#issuecomment-1060276913
  client_body_buffer_size 1m;
  grpc_set_header X-Real-IP $remote_addr;
  client_body_timeout 1h;
  grpc_read_timeout 1h;
  grpc_send_timeout 1h;
  grpc_pass grpc://unix:/dev/xray/socket/vless-grpc.socket;
}
