# Normal reverse proxy settings.
include nginxconfig.io/proxy/proxy_common.conf;

# Proxy timeouts
proxy_connect_timeout              60s;
proxy_send_timeout                 60s;
proxy_read_timeout                 60s;
