compose_file := "compose.yml"

boot:
  docker compose -f {{compose_file}} up -d

down:
  docker compose -f {{compose_file}} down

reboot: down boot

config:
  docker compose -f {{compose_file}} config
