# used in any autoindex file listing config file, 
# simply just add `include             my-patches/file-listing.conf;`
root /public/files/;

location /sub/ {
  include my-patches/file-listing-config.conf;
}

location /sub/good/ {
  include my-patches/file-listing-auth-config.conf;
  include my-patches/file-listing-config.conf;
}