# Add `include             my-patches/ttrss4-patch.conf;` before the `location / {` line
location /snow-miku-server-wow {
    # if ($http_upgrade != "websocket") { # disabled for testing v2ray http upgrade
    #     return 404;
    # }
    proxy_pass            http://host.docker.internal:1081;
    include               nginxconfig.io/proxy/standard_proxy.conf;
}