server {
  listen 81;
  listen [::]:81;
  server_name _;

  # logging
  access_log          /var/log/nginx/fake-to-rss-internal.access.log;
  error_log           /var/log/nginx/fake-to-rss-internal.error.log;

  large_client_header_buffers 4 16k;
  
  location / {
    proxy_pass http://ttrss-app;

    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Host rss.mikufancx.cyou;
    # Show realip in v2ray access.log
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https; # set to https so that ttrss-app is happy
  }
}
