server {
    listen              443 ssl;
    listen              [::]:443 ssl;
    http2               on;
    server_name         ttrss3.mikufancx.cyou;

    # SSL
    ssl_certificate     /etc/ssl/_.mikufancx.cyou.crt;
    ssl_certificate_key /etc/ssl/_.mikufancx.cyou.key;

    # security
    include             nginxconfig.io/security.conf;

    # logging
    access_log          /var/log/nginx/ttrss3.mikufancx.cyou.access.log cloudflare buffer=512k flush=1m;
    error_log           /var/log/nginx/ttrss3.mikufancx.cyou.error.log warn;

    # reverse proxy
    location / {
        proxy_pass            http://unix:/dev/xray/socket/nginx-trojan-tcp.socket;
        include               nginxconfig.io/proxy/standard_proxy.conf;
    }

    # additional config
    include nginxconfig.io/general.conf;
}

# HTTP redirect
server {
    listen      80;
    listen      [::]:80;
    server_name ttrss3.mikufancx.cyou;
    return      301 https://ttrss3.mikufancx.cyou$request_uri;
}