server {
    listen              443 ssl;
    listen              [::]:443 ssl;
    http2               on;
    server_name         wewerss.mikufancx.cyou;

    # SSL
    ssl_certificate     /etc/ssl/_.mikufancx.cyou.crt;
    ssl_certificate_key /etc/ssl/_.mikufancx.cyou.key;

    # security
    include             nginxconfig.io/security.conf;

    # logging
    access_log          /var/log/nginx/wewerss.mikufancx.cyou.access.log cloudflare buffer=512k flush=1m;
    error_log           /var/log/nginx/wewerss.mikufancx.cyou.error.log warn;

    # reverse proxy
    location / {
        resolver              127.0.0.11 [::1]:5353 valid=15s;
        set                   $backend "http://wewe-rss-app:4000";
        proxy_pass            $backend;
        proxy_set_header Host $host;
        include               nginxconfig.io/proxy/standard_proxy.conf;
    }

    # additional config
    include nginxconfig.io/general.conf;
}

# HTTP redirect
server {
    listen      80;
    listen      [::]:80;
    server_name wewerss.mikufancx.cyou;
    return      301 https://wewerss.mikufancx.cyou$request_uri;
}
